<?php

return [
    [
        'title' => 'Dashboard',
        'type'  => 'item',
        'route' => 'dashboard',
        'icon'  => 'tachometer-alt',
        'permission' => 'dashboard',
    ],
    [
        'title' => 'Clients',
        'type'  => 'item',
        'route' => 'customers.index',
        'icon'  => 'users',
        'permission' => 'read-customer',
    ],
    [
        'title' => 'Transporteurs',
        'type'  => 'item',
        'route' => 'transporters.index',
        'icon'  => 'truck-front',
        'permission' => 'read-transporter',
    ],
    [
        'title' => 'Ajouter un dossier',
        'type'  => 'item',
        'route' => 'folders.create',
        'icon'  => 'folder-plus',
        'permission' => 'create-folder',
    ],
    [
        'title' => 'Dossiers',
        'type'  => 'item',
        'route' => 'folders.index',
        'icon'  => 'folder',
        'permission' => 'read-folder',
    ],
    [
        'title' => 'Dossiers en attentes',
        'type'  => 'item',
        'route' => 'pending-folders.index',
        'icon'  => 'folder-plus',
        'permission' => 'read-folder',
    ],
    [
        'title' => 'Dossiers en cours',
        'type'  => 'item',
        'route' => 'progress-folders.index',
        'icon'  => 'folder-open',
        'permission' => 'read-folder',
    ],
    [
        'title' => 'Dossiers fermés',
        'type'  => 'item',
        'route' => 'closed-folders.index',
        'icon'  => 'folder-closed',
        'permission' => 'read-folder',
    ],
    [
    'title' => 'Dépenses',
    'type'  => 'item',
    'route' => 'expenses.index',
    'icon'  => 'money-bill',
    'permission' => 'read-expense',
],
    [
        'title' => 'Factures',
        'type'  => 'item',
        'route' => 'invoices.index',
        'icon'  => 'file-invoice',
        'permission' => 'read-invoice',
    ],
    [
        'title'      => 'Paiements des Factures',
        'type'       => 'item',
        'route'      => 'invoice-payments.index',
        'icon'       => 'hand-holding-usd',
        'permission' => 'read-payment',
    ],
    [
        'title'      => 'Utilisateurs',
        'type'       => 'collapse',
        'icon'       => 'users',
        'permission' => 'read-user',
        'children'   => [
            [
                'title'      => 'Utilisateurs',
                'type'       => 'item',
                'route'      => 'users.index',
                'icon'       => 'list',
                'permission' => 'read-user',
            ],
            [
                'title'      => 'Roles',
                'type'       => 'item',
                'route'      => 'roles.index',
                'icon'       => 'list',
                'permission' => 'read-role',
            ],
        ],
    ],
    [
        'title'      => 'Paramètres',
        'type'       => 'collapse',
        'icon'       => 'cog',
        'permission' => 'update-settings',
        'children'   => [
            [
                'title'      => 'Paramètres générales',
                'type'       => 'item',
                'route'      => 'settings',
                'icon'       => 'cog',
                'permission' => 'update-settings',
            ],
            [
                'title' => 'Types de conteneurs',
                'type'  => 'item',
                'route' => 'container-types.index',
                'icon'  => 'tags',
                'permission' => 'update-settings',
            ],
            [
                'title' => 'Types de documents',
                'type'  => 'item',
                'route' => 'document-types.index',
                'icon'  => 'tags',
                'permission' => 'update-settings',
            ],
            [
                'title' => 'Services',
                'type'  => 'item',
                'route' => 'services.index',
                'icon'  => 'tags',
                'permission' => 'update-settings',
            ],
            [
                'title' => 'TVAs',
                'type'  => 'item',
                'route' => 'tvas.index',
                'icon'  => 'tags',
                'permission' => 'update-settings',
            ],
        ]
    ],
];
